import argparse
from pathlib import Path

import pandas as pd


def load_prediction_csv(input_csv):
    input_csv = Path(input_csv)

    if not input_csv.exists():
        raise FileNotFoundError(f"Prediction CSV not found: {input_csv}")

    return pd.read_csv(input_csv)


def select_representative_cases(
    df,
    output_path,
    top_k=10,
    sort_metric="char_rouge_l_f1",
):
    """
    Select representative reconstruction cases.

    Expected columns:
        reference
        prediction_raw
        prediction_cut
        char_rouge_l_f1
        keyword_recall
        term_hit
        cosine, optional
    """
    required_columns = [
        "reference",
        "prediction_raw",
        "prediction_cut",
        sort_metric,
    ]

    for column in required_columns:
        if column not in df.columns:
            raise ValueError(f"Missing required column: {column}")

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    selected_columns = [
        "reference",
        "prediction_cut",
        "char_rouge_l_f1",
        "keyword_recall",
        "term_hit",
    ]

    if "cosine" in df.columns:
        selected_columns.append("cosine")

    case_df = (
        df[selected_columns]
        .sort_values(by=sort_metric, ascending=False)
        .head(top_k)
        .copy()
    )

    case_df.to_csv(output_path, index=False, encoding="utf-8-sig")

    return case_df


def main():
    parser = argparse.ArgumentParser(
        description="Generate representative case tables from prediction-level CSV files."
    )

    parser.add_argument(
        "--input_csv",
        type=str,
        required=True,
        help="Path to prediction-level CSV generated by eval_pipeline.",
    )

    parser.add_argument(
        "--output_csv",
        type=str,
        default="results/representative_cases.csv",
        help="Output CSV path for selected representative cases.",
    )

    parser.add_argument(
        "--top_k",
        type=int,
        default=10,
        help="Number of representative cases to export.",
    )

    parser.add_argument(
        "--sort_metric",
        type=str,
        default="char_rouge_l_f1",
        help="Metric used to sort representative cases.",
    )

    args = parser.parse_args()

    print("=== Generate Representative Case Table ===")
    print(f"Input CSV: {args.input_csv}")
    print(f"Output CSV: {args.output_csv}")
    print(f"Top K: {args.top_k}")
    print(f"Sort metric: {args.sort_metric}")

    df = load_prediction_csv(args.input_csv)

    case_df = select_representative_cases(
        df=df,
        output_path=args.output_csv,
        top_k=args.top_k,
        sort_metric=args.sort_metric,
    )

    print("\nSaved representative cases to:")
    print(args.output_csv)

    print("\n=== Preview ===")
    print(case_df)


if __name__ == "__main__":
    main()